# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  listforgeapi:
    image: listforgeapi
    build:
      context: .
      dockerfile: src/ListForge.API/Dockerfile
    ports:
      - 5050:5050
